name = "minecraft-voice-chat"
type = "javascript"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.jsx", "src/**/*.js"]

[build.upload]
format = "service-worker"

[env.production]
name = "minecraft-voice-chat-production"
routes = [
  { pattern = "https://minecraft-voice-chat.pages.dev/*" }
]
